Completed react-hot-button component exercise
wang-morris/m3-1222-code-solutions pull request #14
Opened 2022-12-17 23:14 UTC by wang-morris

https://user-images.githubusercontent.com/103090771/208269362-b31e32e6-c8e5-4f6a-b1cf-1f3c9b2fcdfd.mp4

2022-12-17 23:34 UTC, wang-morris commented
Did not use both .jsx files in the first commit.

2022-12-20 05:19 UTC, scbowler requested changes
Good job getting this to work, but here are some things to refactor. Let me know if you have any questions.

2022-12-20 05:19 UTC, scbowler commented on react-hot-button-component/src/hot-button.jsx
> +    this.state = { isClicked: false };
The click count should be stored in state:

```JAVASCRIPT
this.state = {
  count: 0
};
```

2022-12-20 05:19 UTC, scbowler commented on react-hot-button-component/src/hot-button.jsx
> +  }
Here the count should be incremented by 1:
```JAVASCRIPT
handleClick() {
  this.setState({ count: this.state.count + 1 });
}
```

2022-12-20 05:19 UTC, scbowler commented on react-hot-button-component/src/hot-button.jsx
> +  }
In `render` you can use `this.state.count` to determine which class should be applied to the button, then return a single button at the end.
```JAVASCRIPT
render() {
  const count = this.state.count;
  let btnClass;

  if (count < 4) {
    btnClass = 'cold';
  } else if (count < 7) {
    btnClass = 'cool';
  } else if (count < 10) {
    btnClass = 'luke-warm';
  } else if (count < 13) {
    btnClass = 'warm';
  } else if (count < 16) {
    btnClass = 'hot';
  } else {
    btnClass = 'super-hot';
  }

  return (
    <div>
      <button onClick={this.handleClick.bind(this)} className={btnClass}>Hot Button</button>
    </div>
  );
}
```

2022-12-28 04:32 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-12-28 05:04 UTC, merged